version: '3.8'

services:
  mahjong-counter:
    # build: . 会告诉 Docker Compose 在当前目录下查找 Dockerfile 并构建镜像
    build: .
    
    # 为容器命名，方便管理
    container_name: mahjong-counter-app
    
    # 端口映射: 将服务器（宿主机）的 3001 端口映射到容器内部的 3001 端口
    # 格式为 "宿主机端口:容器端口"
    ports:
      - "3001:3001"
      
    # 数据卷 (Volume) 挂载: 这是实现数据持久化的关键
    # - ./server/mahjong_rooms.db:/app/server/mahjong_rooms.db
    # 上面这行配置会将您服务器当前目录下的 server/mahjong_rooms.db 文件
    # 映射到容器内部的 /app/server/mahjong_rooms.db。
    # 这样，所有数据库的读写都会直接发生在您服务器的磁盘上，
    # 即使容器被删除或重建，您的游戏数据也安然无恙。
    # 注意: 第一次启动前，请确保在 server 目录下有一个空的 mahjong_rooms.db 文件，
    # 或者让程序自动创建。为避免权限问题，建议先 `touch server/mahjong_rooms.db`。
    volumes:
      - ./server/data:/app/server/data

    # 重启策略: 确保容器在服务器重启或意外退出后能自动重启
    restart: unless-stopped